from pydantic import BaseModel


class RelatedCasesRequest(BaseModel):
    # CURRENT REQUIRED INPUT FOR `/api/v1/analysis/related-cases`:
    # - file_name: original uploaded file name
    # - summary: summary text generated by the LLM
    #
    # CHANGE THIS LATER ONLY IF NEEDED:
    # - Add fields like jurisdiction, date_range, practice_area when your Courtbase query needs them.
    file_name: str
    summary: str
